# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anoop Singh
email: anoopsinghkhimani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I speak java. Have hands-on experience in SaaS and webservices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anoopsingh.in" # the base hostname & protocol for your site
twitter_username: kenthewala
github_username:  kenthewala

# Build settings
markdown: kramdown
